### ISSUE TITLE
[Feature request] Add support for pack codes

### ISSUE THREAD

**Issue by Cherry** [LiaungYip/Cat-Herder#2]
Firstly, this is really awesome, congrats. It's something I've wanted to do myself for quite some time to improve our automation at NodeCraft, but never gotten around to it. Now onto the actual feature request.

Share codes have become extremely popular for users to distribute a very precise selection of mods. This is especially prevalent in modpacks such as Resonant Rise with a huge abundance of selections, and a huge amount of our support requests currently are for pack installs.

I recently had Ryan from the ATLauncher add a new API end point for share codes which would eventually allow me to automate this entirely, utilising the Configs.xml/json already provided in our CDN, and the output of selected mods from something like https://api.atlauncher.com/v1/share-codes/WA1KDFvi. I've been playing with the idea of a service (primarily for internal use currently) that would allow our agents, or even users directly to input a share code and be provided a package zip for the server.

Let me know if you have any thoughts on this, or if you think it would be a good addition to cat-herder!

PS: Unrelated to this issue, but NodeCDN does now return 404 status codes correctly. :)

**Comment by LiaungYip** [comment]
How do pack share codes work, exactly? You hit a URL like your example `https://api.atlauncher.com/v1/share-codes/<SHARE-CODE>`, and get a JSON response back?

**Comment by Cherry** [comment]
Share codes were introduced to make sharing a set of optionally selected mods a lot easier between friends.

Take Resonant Rise for example, there are hundreds of optional mods available for selection, so I'd create an instance, select which mods I wanted, and then right click that instance image and get a "Share Code", which I could then provide to my friends, and have them install the exact same set of mods. When you install an instance, there's an option in the ATLauncher to "Use share code".

In the same light, that share code can be used to install a server, which makes our job as a service provider also much easier, than having to have clients create a list of potentially hundreds of optional mods.

`https://api.atlauncher.com/v1/share-codes/<SHARE-CODE>` should allow a tool like this to combine its output, alongside the regular pack's Configs.xml/json to create an identical server package, with the correct share code.

**Comment by LiaungYip** [comment]
@Cherry I see how that would add value to your service, and I agree it is a worth-while feature to have.

To be honest, I have limited time, and don't use Share Codes myself, so I don't plan to work on this immediately. I would welcome contributions from others to fill this gap. Note the script is MIT licensed.

**Comment by Cherry** [comment]
Makes sense. Thanks for your time! :)

As previously mentioned, I've been toying with my own implementation after having the API endpoint added, but ran across your implementation via your website. Python isn't really my thing, but thanks once again.

**Comment by LiaungYip** [comment]
@Cherry:
1. Share codes appear to be used for client installs only. I can't find an option in the ATLauncher GUI to generate a share code for a server install. (In fact, I can't find the server tab at all! Was the server tab removed from ATL?) Are share codes helpful when installing a server?
2. Is there any documentation for the Share Code API? I can see at https://api.atlauncher.com/v1/share-codes/QtDNnlfZ, for example, there is a variable called `used` whose purpose is not explained. `message` is also unexplained.

**Comment by Cherry** [comment]
@LiaungYip 
1. Share codes can be used on packs that support servers just fine. Make sure you're using the most recent version of the launcher (3.2.3.1 at time of writing), and for example with Resonant Rise:
   - http://jross.me/l/mnu3k -> hit "create server", and select version
   - http://jross.me/l/zl2ma -> bottom right, "use share code"
     Not all packs support servers, or customisable servers so the "create server" button either won't display, or will just download a very specific set of non customisable mods, such as with Madpack.
2. http://wiki.atlauncher.com/api:share_code_object. `message` will only be populated if there's an error as per http://wiki.atlauncher.com/api:information#basic_returned_information

PS. Just a friendly heads up, but [Ryan](https://github.com/RyanTheAllmighty) generally doesn't approve of people doing things like this without talking to him first. I'd recommend shooting him an email, as you definitely have a nice system here.

**Comment by LiaungYip** [comment]
I have contacted Ryan by email. He has no objection to this project at this time. Work will proceed.

**Comment by Cherry** [comment]
Fantastic :) Let me know if you need any further input!

**Comment by LiaungYip** [comment]
@Cherry - As of merge #4, `cat-herder` should now support the use of "share codes" via the `install-from-share-code` option. I invite you to test it out. Please open new issue(s) if/when you discover bugs.
