### ISSUE TITLE
atlauncher_import.py:72 fails when returned data doesn't contain an md5 hash

### ISSUE THREAD

**Issue by lawsonjl** [LiaungYip/Cat-Herder#5]
Sometimes ATLauncher's system serves up an entry that is missing the 'md5' attribute. In this case, the script fails with a KeyError.

I slightly modified the atlauncher_import.py to show me what it's getting back:

``` bash
Adding mod InventoryTweaks-1.59-dev-156.jar to download list - http://download.nodecdn.net/containers/atl/packs/ResonantRise/files/3.x/InventoryTweaks-1.59-dev-156.jar
{
  'website':'http://journeymap.techbrew.net/',
  'group':'minimap',
  'name':'Journey Map - Fairplay',
  'url':'http://minecraft.curseforge.com/mc-mods/32274-journeymap-32274/files/2221282/download',
  'type':'mods',
  'selected':'no',
  'recommended':'no',
  'server':'no',
  'donation':'https://www.patreon.com/techbrew?ty=h',
  'version':'5.0.1',
  'file':'JourneyMap5.0.1_FairPlay_MC1.7.10.jar',
  'authors':'techbrew',
  'download':'direct',
  'optional':'yes',
  'description':'JourneyMap is a client mod for Forge which maps your Minecraft world in real-time as you explore. You can view the map in a web browser or in-game as a Minimap or full-screen.'
}
```

I may or may not submit a pull request to fix it, it depends on how much time I have. At the very least I'm raising this issue so I have something to reference in that pull request.

**Comment by LiaungYip** [comment]
To be honest, I'm surprised anyone even knows about, or uses, this thing!

**Comment by LiaungYip** [comment]
Note, [file_handling.py#L48](https://github.com/LiaungYip/Cat-Herder/blob/master/file_handling.py#L48) already contains code that handles an MD5 hash of `None`. It's probably sufficient to modify [atlauncher_import.py#L71](https://github.com/LiaungYip/Cat-Herder/blob/master/atlauncher_import.py#L71) to set `f['download_md5']` to `None` if there's no MD5 attribute.

**Comment by lawsonjl** [comment]
That is precisely what I have done. I'll submit a pull request in a few
minutes.

This script has been invaluable in setting up a minecraft server deployed
by vagrant =)
