### ISSUE TITLE
[Bug] CatHerder ignores <noconfigs> tag and errors out

### ISSUE THREAD

**Issue by GazbonicAcid** [LiaungYip/Cat-Herder#8]
CatHerder ignores the \<noconfigs\> tag.
This causes the installation to fail and error out saying the config zip does not exist.

**Comment by LiaungYip** [comment]
@GazbonicAcid Thanks for reporting! Can you please post an example command that reproduces the bug?

**Comment by GazbonicAcid** [comment]
I believe the command I tried was

> ./cat_herder.py -p ColonialFrontier -v preAlpha_1.0.0 -i /var/games/minecraft/servers/colonialfrontier/

However it can be reproduced only with specific pack versions that do **_NOT_** have a global config uploaded.
I basically had to upload an empty zip file as a global config to get the above command to work.
Which means it won't reproduce the bug anymore.

**Comment by GazbonicAcid** [comment]
I know it ignores the "\<noconfigs\>true\</noconfigs\>" tag in pack xml,
because the error stated that the global config zip was not a zip file.
It didn't say it couldn't find the global config zip,
it said that the global config zip wasn't a zip.
However since that particular version of my pack doesn't have a global config and had the "\<noconfigs\>true\</noconfigs\>" tag in it,
catherder shouldn't have tried getting a global config zip.
